In [1]:
#1. Sayılardan oluşan bir boyutlu array oluşturun. Arrayi oluştururken sayıların veri tipini integer olarak belirtelim.

#Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakalım.

import numpy as np

array = np.array([1, 2, 3, 4, 5], dtype=int)

print(array)

[1 2 3 4 5]


In [3]:
array.size

5

In [8]:
array.shape

(5,)

In [9]:
type(array)

numpy.ndarray

In [16]:
#2. Aşağıda verilen iki boyutlu ve üç boyutlu arrayi oluşturalım. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşalım.

#İki boyutlu array:
[[1,2,6,7],
[4,3,9,5]]
#Üç boyutlu array:
[[[7,5,14],[21,8,11]],
[[8,6,20],[14,3,9]]]


array1 = np.array([[1, 2, 6, 7],
                   [4, 3, 9, 5]])

array2 = np.array([[7, 5, 14],
                   [21, 8, 11],
                   [8, 6, 20],
                   [14, 3, 9]])

print(array1)
print(array2)

[[1 2 6 7]
 [4 3 9 5]]
[[ 7  5 14]
 [21  8 11]
 [ 8  6 20]
 [14  3  9]]


In [19]:
array1.shape

(2, 4)

In [20]:
array2.shape

(4, 3)

In [21]:
array1.size

8

In [22]:
array2.size

12

In [ ]:
#3. İstenilen elamanlara ulaşmak için arrayler üzerinde indexleme işlemi yapalım.
#İki boyutlu arraydaki 2 elemanına ulaşalım.
#İki boyutlu arraydaki 7 elemanına ulaşalım.
#Üç boyutlu arraydaki 9 elemanına ulaşalım.
#Üç boyutlu arraydaki 5 elemanına ulaşalım.

In [23]:
array1

array([[1, 2, 6, 7],
       [4, 3, 9, 5]])

In [43]:
array1[0,1]

np.int64(2)

In [44]:
array1[0,3]

np.int64(7)

In [45]:
array2

array([[ 7,  5, 14],
       [21,  8, 11],
       [ 8,  6, 20],
       [14,  3,  9]])

In [46]:
array2[3,2]

np.int64(9)

In [47]:
array2[0,1]

np.int64(5)

In [ ]:
#4. Arrayler üzerinde slicing işlemi uygulayalım.

#İki boyutlu arraydaki 2,6 elemanlarına ulaşalım.
#İki boyutlu arraydaki 3,9,5 elemanlarına ulaşalım.
#Üç boyutlu arraydaki 21,8,11 elemanlarına ulaşalım.
#Üç boyutlu arraydaki 6,20 elemanlarına ulaşalım.

In [48]:
array1

array([[1, 2, 6, 7],
       [4, 3, 9, 5]])

In [57]:
array1[0,1:3]

array([2, 6])

In [61]:
array1[1,1:4]

array([3, 9, 5])

In [62]:
array2

array([[ 7,  5, 14],
       [21,  8, 11],
       [ 8,  6, 20],
       [14,  3,  9]])

In [63]:
array2[1]

array([21,  8, 11])

In [64]:
array2[2,1:3]

array([ 6, 20])

In [ ]:
#5. 5 satır 3 sütunluk sıfırlardan ve birlerden oluşan iki tane iki boyutlu array oluşturalım. 
#Bu arrayleri satır ve sütun bazında birleştirelim.